// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.4
// source: chitty-chat/proto/proto.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Chat_SendAndReceive_FullMethodName = "/simpleGuide.Chat/SendAndReceive"
)

// ChatClient is the client API for Chat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatClient interface {
	SendAndReceive(ctx context.Context, opts ...grpc.CallOption) (Chat_SendAndReceiveClient, error)
}

type chatClient struct {
	cc grpc.ClientConnInterface
}

func NewChatClient(cc grpc.ClientConnInterface) ChatClient {
	return &chatClient{cc}
}

func (c *chatClient) SendAndReceive(ctx context.Context, opts ...grpc.CallOption) (Chat_SendAndReceiveClient, error) {
	stream, err := c.cc.NewStream(ctx, &Chat_ServiceDesc.Streams[0], Chat_SendAndReceive_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &chatSendAndReceiveClient{stream}
	return x, nil
}

type Chat_SendAndReceiveClient interface {
	Send(*SentMessage) error
	Recv() (*ReceivedMessage, error)
	grpc.ClientStream
}

type chatSendAndReceiveClient struct {
	grpc.ClientStream
}

func (x *chatSendAndReceiveClient) Send(m *SentMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chatSendAndReceiveClient) Recv() (*ReceivedMessage, error) {
	m := new(ReceivedMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChatServer is the server API for Chat service.
// All implementations must embed UnimplementedChatServer
// for forward compatibility
type ChatServer interface {
	SendAndReceive(Chat_SendAndReceiveServer) error
	mustEmbedUnimplementedChatServer()
}

// UnimplementedChatServer must be embedded to have forward compatible implementations.
type UnimplementedChatServer struct {
}

func (UnimplementedChatServer) SendAndReceive(Chat_SendAndReceiveServer) error {
	return status.Errorf(codes.Unimplemented, "method SendAndReceive not implemented")
}
func (UnimplementedChatServer) mustEmbedUnimplementedChatServer() {}

// UnsafeChatServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatServer will
// result in compilation errors.
type UnsafeChatServer interface {
	mustEmbedUnimplementedChatServer()
}

func RegisterChatServer(s grpc.ServiceRegistrar, srv ChatServer) {
	s.RegisterService(&Chat_ServiceDesc, srv)
}

func _Chat_SendAndReceive_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChatServer).SendAndReceive(&chatSendAndReceiveServer{stream})
}

type Chat_SendAndReceiveServer interface {
	Send(*ReceivedMessage) error
	Recv() (*SentMessage, error)
	grpc.ServerStream
}

type chatSendAndReceiveServer struct {
	grpc.ServerStream
}

func (x *chatSendAndReceiveServer) Send(m *ReceivedMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chatSendAndReceiveServer) Recv() (*SentMessage, error) {
	m := new(SentMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Chat_ServiceDesc is the grpc.ServiceDesc for Chat service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Chat_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "simpleGuide.Chat",
	HandlerType: (*ChatServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendAndReceive",
			Handler:       _Chat_SendAndReceive_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "chitty-chat/proto/proto.proto",
}
